### ISSUE TITLE
Occasionally misses an intersection taking place

### ISSUE THREAD

**Issue by bengallienne** [Akryum/vue-observe-visibility#12]
Hi, 

We are checking out the directive and were wondering if you are occasionally finding it 'misses' something arriving in the viewport until it is scrolled off the screen and back on again. We are looking in to what might cause it and will submit further if we find a bug ourselves, but have you had any experience of this before? Speed of scrolling does not seem to make a difference.

Thanks for any advice you can give,

Ben

**Comment by codezomb** [comment]
Definitely seeing this as well.

**Comment by alexbudure** [comment]
Having the same issue

**Comment by codezomb** [comment]
I wonder if #9 could help w/ this problem.

**Comment by Nazcain** [comment]
Same here.
@bengallienne @alexbudure Did you find a possible solution?

**Comment by bengallienne** [comment]
Yes, in the end we edited the threshold prop to check at 0.5, 0.75, 1, and this resolved the issue as the item was being checked multiple times as it moved in to request.

Thanks,

Ben

**Comment by SerikDM** [comment]
Have same issue, #9 doesn't fix it completely
