### ISSUE TITLE
Get Directive Target Element

### ISSUE THREAD

**Issue by nickpoulos** [Akryum/vue-observe-visibility#125]
Maybe not the right forum for this question, but is it possible to get the calling element from the directive inside the callback method?  

I know I could pass an id/selector as an optional argument and get the element that way, but didn't like the way that felt, as I have 100+ elements to do this for. 

I tried passing the $event var as a custom argument but that did not work, as it doesn't seem to be a true event.  So is there something similar to '$event' variable that can be passed to the method so I can get the target?  Ex:
 
```
<div v-observe-visibility="(isVisible, entry) => 
      myCallbackMethod(isVisible, entry, $event)">

function myCallbackMethod (event) { 
   let element = event.target 
   element.classList.add('visible');
} 
```

**Comment by Jesus82** [comment]
I have exactly the same user case, there should be away to do this without a method in order to work with big lists of items.

**Comment by Akryum** [comment]
`entry.target` [docs](https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserverEntry)
