### ISSUE TITLE
Callback is always called when "once" is set and element is invisible

### ISSUE THREAD

**Issue by sebastien-prudhomme** [Akryum/vue-observe-visibility#167]
Hi,

I was surprised that even with the `once` option, the callback is called when an element is invisible when it's just created.

Is this a normal behavior?

**Comment by raffi1300** [comment]
Check the isVisible property that's being passed into the callback function. It's called once at first I guess when it's initialized, but it's not set as visible. Once you scroll into view, it will set it as visible and it will only call it once.

**Comment by sebastien-prudhomme** [comment]
As i no more use that package and can't provide any feedback, i prefer to close this issue.
