### ISSUE TITLE
Options Object Doesn't Work in Nuxt

### ISSUE THREAD

**Issue by jpt** [Akryum/vue-observe-visibility#19]
When using an options object with vue-observe-visibility using Nuxt, I get the following error: `observe-visibility directive expects a function as the value`

It works fine if I pass it a function without an options object.

**Comment by Akryum** [comment]
Could you check that you are on latest version?

**Comment by jpt** [comment]
Ah, apologies, I was on 0.3.1 rather than 0.4! I'll close the issue, thanks!
