### ISSUE TITLE
The jsfiddle is not working (Uncaught ReferenceError: Vue is not defined)

### ISSUE THREAD

**Issue by shoegazerwithak** [Akryum/vue-observe-visibility#2]
Change this:
`<script src="https://unpkg.com/vue@next/dist/vue.js"></script>`
to this:
`<script src="https://unpkg.com/vue@latest/dist/vue.js"></script>`

Updated jsfiddle: https://jsfiddle.net/o2bpoj5c/

**Comment by Akryum** [comment]
Thankx, updated the fiddle.
