### ISSUE TITLE
Event firing 2 times

### ISSUE THREAD

**Issue by rSammy** [Akryum/vue-observe-visibility#20]
When scrolling fast VisibilityChanged is firing 2 times.

**Comment by Akryum** [comment]
Well, if the browser Intersection Observer decides to do so... ¯\_(ツ)_/¯

**Comment by maximilliangeorge** [comment]
For the record, I had an issue with the observer callback firing when manipulating classes of nested elements. This isn't a problem with the plugin though. Working towards a solution.
