### ISSUE TITLE
How to use in Vue3 ? (rc.2)

### ISSUE THREAD

**Issue by cimpok** [Akryum/vue-observe-visibility#219]
_Yes, I know Vue3 is not released yet. But 1. you will have to support it anyway very soon, 2. what about being the very first visibility observing component to support it?_

I tried the following in main.js:
```
import { createApp } from 'vue'
import App from './App.vue'
import VueObserveVisibility from 'vue-observe-visibility'

const app = createApp(App)
app.component('observe-visibility', VueObserveVisibility)
app.mount('#app')
```

Also tried  `app.directive('observe-visibility', VueObserveVisibility.ObserveVisibility)  `instead of the component line.  In both cases it gets compiled and runs with no errors but the callback is not called when the div is scrolled in/out of view.

What I am doing wrong? / If it is not supposed to work under Vue3 what is the cause.  Thank you.

**Comment by fatalis** [comment]
```
import { ObserveVisibility } from 'vue-observe-visibility';
app.directive('observe-visibility', {
  beforeMount: (el, binding, vnode) => {
    vnode.context = binding.instance;
    ObserveVisibility.bind(el, binding, vnode);
  },
  update: ObserveVisibility.update,
  unmounted: ObserveVisibility.unbind,
});

```

**Comment by avarayr** [comment]
In case you're using typescript

File: **main.ts** or wherever you do createApp
```typescript
createApp(App)
  .directive("observe-visibility", {
    beforeMount: (el, binding, vnode) => {
      (vnode as any).context = binding.instance
      ObserveVisibility.bind(el, binding, vnode)
    },
    updated: ObserveVisibility.update,
    unmounted: ObserveVisibility.unbind,
  })
  .mount("#app")

```

**Comment by cimpok** [comment]
Thank you both this way it works.

**Comment by jetcamp** [comment]
I get error with @fatalis approach:

`Uncaught (in promise) TypeError: Failed to execute 'observe' on 'IntersectionObserver': parameter 1 is not of type 'Element'.`

using it like in vue 2;

```
  <div class="destination-slider-block" v-if="destinationsData" v-observe-visibility="{
      callback: isVisible,
      once: true,
    }"></div>
```

**Comment by jetcamp** [comment]
> I get error with @fatalis approach:
> 
> `Uncaught (in promise) TypeError: Failed to execute 'observe' on 'IntersectionObserver': parameter 1 is not of type 'Element'.`
> 
> using it like in vue 2;
> 
> ```
>   <div class="destination-slider-block" v-if="destinationsData" v-observe-visibility="{
>       callback: isVisible,
>       once: true,
>     }"></div>
> ```

Just found that lazy loading image is causing it with this package @techassi/vue-lazy-image

**Comment by musashiM82** [comment]
hi
I get following error, using above way 
```
GlobalVue.use is not a function

```
at Module../node_modules/vue-observe-visibility/dist/vue-observe-visibility.esm.js (vue-observe-visibility.esm.js:302)

why?
thanks in advance

**Comment by kyrylo93** [comment]
@fatalis, unfortunately, i can't say that your code example works

**Comment by kyrylo93** [comment]
@fatalis ,
`Uncaught (in promise) TypeError: vue_observe_visibility__WEBPACK_IMPORTED_MODULE_18__.ObserveVisibility.bind is not a function
    at beforeMount`

**Comment by kyrylo93** [comment]
@fatalis ,
for me works in such way
`app.directive('observe-visibility', {
  beforeMount: ObserveVisibility.beforeMount,
  update: ObserveVisibility.update,
  unmounted: ObserveVisibility.unbind
})`

**Comment by issei-m** [comment]
@fatalis Thanks for the workaround!
But this code is not yet enough, when `updated` is fired, the error where `vnode.context` is undefined but referred `$nextTick` method occurs. 

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '$nextTick')
    at VisibilityState.createObserver (vue-observe-visibility.esm.js?85fe:196:1)
    at update (vue-observe-visibility.esm.js?85fe:251:1)
    at callWithErrorHandling (VM161431 runtime-core.esm-bundler.js:283:22)
    at callWithAsyncErrorHandling (VM161431 runtime-core.esm-bundler.js:292:21)
    at invokeDirectiveHook (VM161431 runtime-core.esm-bundler.js:3865:13)
    at Array.eval (VM161431 runtime-core.esm-bundler.js:4884:25)
    at flushPostFlushCbs (VM161431 runtime-core.esm-bundler.js:481:47)
    at flushJobs (VM161431 runtime-core.esm-bundler.js:526:9)
```

So we need the same trick as we do in `beforeMount` like this:

```javascript
app.directive('observe-visibility', {
  beforeMount: (el, binding, vnode) => {
    vnode.context = binding.instance
    ObserveVisibility.bind(el, binding, vnode)
  },
  updated: (el, binding, vnode) => {
    vnode.context = binding.instance
    ObserveVisibility.update(el, binding, vnode)
  },
  unmounted: ObserveVisibility.unbind,
})
```

This tweak works well on my env.

**Comment by musiwei** [comment]
None of the examples above works for me.  Any plan to add official vue 3 support since it's the official version now?

**Comment by Akryum** [comment]
https://github.com/Akryum/vue-observe-visibility/tree/next

**Comment by NPBogdan** [comment]
> ```
> import { ObserveVisibility } from 'vue-observe-visibility';
> app.directive('observe-visibility', {
>   beforeMount: (el, binding, vnode) => {
>     vnode.context = binding.instance;
>     ObserveVisibility.bind(el, binding, vnode);
>   },
>   update: ObserveVisibility.update,
>   unmounted: ObserveVisibility.unbind,
> });
> ```
 
Thank you very much
