### ISSUE TITLE
bug: undefined is not an object (this.bind)

### ISSUE THREAD

**Issue by daniele-orlando** [Akryum/vue-observe-visibility#22]
```
[Vue warn]: Error in directive observe-visibility update hook: "TypeError: undefined is not an object (evaluating 'this.bind')"
```
`this` is not available inside a directive hook.

See
https://github.com/Akryum/vue-observe-visibility/blob/0895390eedd6ea3cdff99477bc54bb90859098a2/src/directives/observe-visibility.js#L68

**Comment by edcousins** [comment]
Any news on this issue?

**Comment by tjallingt** [comment]
@daniele-orlando @edcousins @Akryum I submitted a pull request, if possible can you check if this fixes the problem?
