### ISSUE TITLE
Once not working with Throttle

### ISSUE THREAD

**Issue by Xationch** [Akryum/vue-observe-visibility#33]
When I use both options at the same time the Once option does not work. Is this normal behavior? Each separately works very well.

```
v-observe-visibility="{
   callback: visibilityChanged,
   throttle: 300,
   once: true
}"
```

**Comment by nicholaszuccarelli** [comment]
Same issue for me too.

**Comment by Xationch** [comment]
@nicholaszuccarelli You try to use a different key attr on each element using the once? ```key="a"```
```key="b"```
