### ISSUE TITLE
[Q] Conditional observable

### ISSUE THREAD

**Issue by LexSwed** [Akryum/vue-observe-visibility#34]
I have dynamic detection on whether to observe element or not, based on computed property. I don't see on sources that it removes element from observables on `{ value }` change. Interestingly, I first noticed some issues in my app, decided to fork and start using my fork, but then I found out that the issue was in other place and returned back to your version and it works fine. But still, I'm curious about dynamic directive binding.

Link to a fork: https://github.com/Akryum/vue-observe-visibility/compare/master...LexSwed:master

**Comment by Akryum** [comment]
Implemented in https://github.com/Akryum/vue-observe-visibility/commit/759e5d2ddc15d6502a17ce6f1e378cb7c1cd2af5
