### ISSUE TITLE
Problem on safari using nuxt

### ISSUE THREAD

**Issue by shutt** [Akryum/vue-observe-visibility#36]
I'm using this on a nuxt project and i'm not able to make it work on safari or mobile (ios) does anyone was able to set it up correctly on nuxt?

**Comment by manniL** [comment]
duplicate of https://github.com/Akryum/vue-observe-visibility/issues/26

**Comment by toleberdyyeva** [comment]
Does anyone solved this problem ? Cause I'm using it in nuxt project , And error still occurs.

**Comment by Akryum** [comment]
Duplicate of #26
