### ISSUE TITLE
Visibility function is not called until scroll completely stops (iOS)

### ISSUE THREAD

**Issue by p3v9d5ui** [Akryum/vue-observe-visibility#43]
I'm using this plugin in a Cordova app running on iOS. In this environment, the visibility callback is not triggered while the user is still scrolling (even if the user has lifted their finger, and the scroll slows to a stop). Only when the scroll completely stops is the callback triggered. Is there any way to get around this behaviour? I want the callback to be triggered immediately when the element becomes visible.

**Comment by Akryum** [comment]
I guess this is due to Safari. I'm using a standard API, nothing more.
