### ISSUE TITLE
Pass parameters

### ISSUE THREAD

**Issue by liepaja** [Akryum/vue-observe-visibility#5]
Is there a way to pass parameters to the function?

**Comment by Akryum** [comment]
What do you mean? Do you have an example?

**Comment by liepaja** [comment]
`<div id="app">
  <button @click="show = !show">Toggle</button>
  <label>
    <input type="checkbox" v-model="isVisible" disabled/> Is visible?
  </label>
  <div ref="test" v-show="show" v-observe-visibility="visibilityChanged(parameter)">Hello world!</div>
</div>

<script>
new Vue({
  el: '#app',
  data: {
    show: true,
    isVisible: true
  },
  methods: {
    visibilityChanged: function (isVisible, entry, parameter) {
      this.isVisible = isVisible
      console.log(entry)
    }
  }
})
</script>`

Usually only 1 native parameter is passed and the solution is to have method($event, parameter), this time there are two. Thanks for fast respones

**Comment by Akryum** [comment]
You can do `v-observe-visibility="(isVisible, entry) => visibilityChanged(isVisible, entry, parameter)"`

**Comment by liepaja** [comment]
Thanks!

**Comment by Akryum** [comment]
I added [a section](https://github.com/Akryum/vue-observe-visibility/blob/master/README.md#usage) in the README about that.

**Comment by Saurou** [comment]
> You can do `v-observe-visibility="(isVisible, entry) => visibilityChanged(isVisible, entry, parameter)"`

would you still be able to pass `throttle` and `once` with this?

**Comment by kthiele** [comment]
> > You can do `v-observe-visibility="(isVisible, entry) => visibilityChanged(isVisible, entry, parameter)"`
> 
> would you still be able to pass `throttle` and `once` with this?

I've done it like this:
```
v-observe-visibility="{
    callback: (isVisible, entry) => visibilityChanged(isVisible, entry, parameter),
    once: true,
    throttle: 300,
}"
```
