### ISSUE TITLE
Why I can't  add  array to threshold?

### ISSUE THREAD

**Issue by Kostyaval** [Akryum/vue-observe-visibility#66]
As I understand it is possible to do in [IntersectionObserver](https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserver/IntersectionObserver#Parameters)

**Comment by Akryum** [comment]
It's not currently supported.

**Comment by Akryum** [comment]
The latest release allow you to pass an array of threshold but it is then considered as `0` for the directive. You still have access to the `entry` as the second callback argument.
