### ISSUE TITLE
`rootMargin` has no effect

### ISSUE THREAD

**Issue by b12k** [Akryum/vue-observe-visibility#69]
Greetings,
I have a small problem related to `rootMargin`.
I have a lazy image component:
```html
<img
  :src="loadedSrc"
  v-observe-visibility="{
    rootMargin,
    callback: handleVisibilityChange,
  }"
  class="base-image"
>
```
where `rootMargin` is a computed property related to a component height:
```javascript
...
computed: {
  rootMargin() {
    const { rootMarginBottom } = this;
    return `0px 0px ${rootMarginBottom}px 0px`;
  },
},
mounted() {
  const { $el } = this;
  this.$nextTick(() => {
    this.rootMarginBottom = $el.getBoundingClientRect().height * 3;
  });
}
...
```

The problem is that `rootMargin` has no effect on when `callback` is toggled. It is always when element is fully in the viewport. As you may guess I'm trying to preload image before it enters a viewport.

It also works exactly the same way if i hardcode the `rootMargin`. It feels like its ignored...

Can some one give me a hint where the problem is?

Thank you in advance!

**Comment by Akryum** [comment]
You are not using the correct options: https://github.com/Akryum/vue-observe-visibility#intersectionobserver-options

**Comment by b12k** [comment]
OMG! What a stupid mistake =)
Thank you very much!
Everything works as expected now.

**Comment by mlnmln** [comment]
@b12k I'm having the same problem (preloading images before they enter the viewport) and can't get this working. Could you provide the options you used? Thanks in advance. 

Here are my current take. 

```
          v-observe-visibility="{
            callback: visibilityChanged,
            intersection: {
              rootMargin: '100px 100px 100px 100px'
            },
            once: false
```
          }"
