### ISSUE TITLE
Adding args to function

### ISSUE THREAD

**Issue by kleinjm** [Akryum/vue-observe-visibility#7]
How would I go about adding an argument to the function such as
```
      <li v-for="person in persons"
          :key="person.id"
          v-observe-visibility="visibilityChanged(person)">
```
?
I'm seeing `Error in directive observe-visibility bind hook: "Error: observe-visibility directive expects a function as the value"`. I just don't know how to pass in an arg and play nicely with the `isVisible` and `entry` args. I'm sure this is just my lack of Vue knowledge.

Thanks in advance for the help. Great package!

**Comment by Akryum** [comment]
See [#5](https://github.com/Akryum/vue-observe-visibility/issues/5#issuecomment-326571990).

**Comment by kleinjm** [comment]
Thanks for the fast reply!
